# Generated by Django 5.0.6 on 2024-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_holiday_slot_attendance_periods_advisor_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='periods',
            field=models.IntegerField(default=1715753708.794521),
        ),
    ]
