# Generated by Django 5.0.6 on 2024-05-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_attendance_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='periods',
            field=models.IntegerField(default=1715753903),
        ),
    ]
