# Generated by Django 5.0.6 on 2024-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_attendance_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='dates',
            field=models.CharField(max_length=10),
        ),
    ]
